### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by jxayzly11** [AppLovin/AppLovin-Android-SDK-Demo#3]
Hello friend,

I used 6.2.3 SDK,want to show AppLovinInterstitialAd,you can see the code below,when "AL: Load Success" print,I was called show(),but nothing happened on screen.Please help me!!!!!
![image](https://cloud.githubusercontent.com/assets/7018360/16334449/a56989bc-3a33-11e6-8b33-b5521bd8322e.png)
![image](https://cloud.githubusercontent.com/assets/7018360/16334454/ab088fa8-3a33-11e6-969e-1de62670b2c3.png)

**Comment by umair6** [comment]
Facing same issue as posted by @jxayzly11 . Any fix to this?

**Comment by thomasmso** [comment]
Hi @umair6, what SDK version are you using?

**Comment by umair6** [comment]
@thomasmso I am using latest SDK 6.2.4. 
When I was using 6.2.3, this issue was very often. With 6.2.4, I am able to reproduce it Nexus 9 (Android 6.0.1) and Samsung S6   (Android 6 . 0.1).

**Comment by thomasmso** [comment]
@umair6 Can you email me at thomas.so@applovin.com? We can analyze the issue more in-depth there.

**Comment by umair6** [comment]
@thomasmso  Email sent.
