### ISSUE TITLE
How to gracefully shutdown AppLovin threads

### ISSUE THREAD

**Issue by gubatron** [AppLovin/AppLovin-Android-SDK-Demo#4]
Hi there from FrostWire!

Our android app has an exit feature (something not common on Android but very necessary to our userbase)

We were wondering if you have a way to gracefully shutdown the different background threads we see applovin creates when initialized.

If there isnt one, would it be possible to add a `.shutdown()` method so that we can do a clean release of these threads?

**Comment by gubatron** [comment]
Here's a list of the threads we see from AppLovin:

```
Thread (#424) 'AppLovinSdk:postbacks:GT8R'
Thread (#3f7) 'AppLovinSdk:back:GT8R'
Thread (#3f4) 'AppLovinSdk:main:GT8R'
```

**Comment by thomasmso** [comment]
Thank you very much for suggesting this feature. Our SDK is passive most of the time; it is using background threads to pre-cache ads at initialization and then to load more ads when pre-cached ads are displayed.

However, we shall consider adding a shutdown method in the future releases.
